### ISSUE TITLE
Docker部署成功，但回复一直显示network error该如何解决

### ISSUE THREAD

**Issue by bosconb** [nashsu/FreeAskInternet#18]
按照[docker-compose](https://github.com/nashsu/FreeAskInternet/blob/main/docker-compose.yaml)部署成功，但无论发什么都是network error，后台应该都启动了的。

![image](https://github.com/nashsu/FreeAskInternet/assets/47100031/fc3421ef-c28a-4a7c-a331-0250a5663357)
![image](https://github.com/nashsu/FreeAskInternet/assets/47100031/d1355553-4b79-4a25-8970-b5ac7b8d3e6c)

**Comment by wolfg1969** [comment]
首先检查能正常访问 searxng 依赖的 search engine，比如 www.google.com, www.google.com.hk, duckduckgo.com, api.qwant.com, search.brave.com, zh.wikipedia.org, query.wikidata.org 等等，具体可以查看 searxng 容器的日志。
然后确认 compose 文件所在目录下 searxng/settings.yml 中启用了 json 格式输出
```yml
formats:
    - html
    - json
```
如果没有启用 json 格式，backend 容器的日志中可以看到访问 searxng 有 403 错误。

**Comment by bosconb** [comment]
> 首先检查能正常访问 searxng 依赖的 search engine，比如 [www.google.com](http://www.google.com), [www.google.com.hk](http://www.google.com.hk), duckduckgo.com, api.qwant.com, search.brave.com, zh.wikipedia.org, query.wikidata.org 等等，具体可以查看 searxng 容器的日志。 然后确认 compose 文件所在目录下 searxng/settings.yml 中启用了 json 格式输出
> 
> ```yaml
> formats:
>     - html
>     - json
> ```
> 
> 如果没有启用 json 格式，backend 容器的日志中可以看到访问 searxng 有 403 错误。

谢谢老哥指点，已经启用json格式输出了，不过只有Reference  linking，好像跟很多朋友也[反馈了这个问题](https://github.com/nashsu/FreeAskInternet/issues/7)
![image](https://github.com/nashsu/FreeAskInternet/assets/47100031/35dd1921-faab-4942-a896-6a00432302f3)

**Comment by wolfg1969** [comment]
这似乎是访问 chatgpt 的问题

**Comment by 907739769** [comment]
是因为你没有下载两个配置文件
![image](https://github.com/nashsu/FreeAskInternet/assets/27858369/d68f1714-f2c9-4d9f-b171-9a07aaf886fa)

![image](https://github.com/nashsu/FreeAskInternet/assets/27858369/f0f2acc8-8ab2-429e-8afc-497cfdcbb17d)

**Comment by wensley** [comment]
刚更新镜像 重新部署了，用的甲骨文美区，
`{
  "error": true,
  "message": "Error in input stream"
}
`
`{
  "error": true,
  "message": "empty response"
}
`
```
 +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "/usr/local/lib/python3.9/site-packages/sse_starlette/sse.py", line 270, in wrap
    |     await func()
    |   File "/usr/local/lib/python3.9/site-packages/sse_starlette/sse.py", line 251, in stream_response
    |     async for data in self.body_iterator:
    |   File "/usr/local/lib/python3.9/site-packages/starlette/concurrency.py", line 65, in iterate_in_threadpool
    |     yield await anyio.to_thread.run_sync(_next, as_iterator)
    |   File "/usr/local/lib/python3.9/site-packages/anyio/to_thread.py", line 56, in run_sync
    |     return await get_async_backend().run_sync_in_worker_thread(
    |   File "/usr/local/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 2144, in run_sync_in_worker_thread
    |     return await future
    |   File "/usr/local/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 851, in run
    |     result = context.run(func, *args)
    |   File "/usr/local/lib/python3.9/site-packages/starlette/concurrency.py", line 54, in _next
    |     return next(iterator)
    |   File "/app/server.py", line 152, in predict
    |     for token in free_ask_internet.ask_internet(query=query):
    |   File "/app/free_ask_internet.py", line 219, in ask_internet
    |     content_list = search_web_ref(query,debug=debug)
    |   File "/app/free_ask_internet.py", line 99, in search_web_ref
    |     raise ex
    |   File "/app/free_ask_internet.py", line 39, in search_web_ref
    |     response.raise_for_status()
    |   File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    |     raise HTTPError(http_error_msg, response=self)
    | requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http://searxng:8080/?q=%3Aall+%21general+%E6%88%91%E6%83%B3%E8%AE%A9%E4%BD%A0%E5%81%9A%E4%B8%80%E4%B8%AA%E6%97%85%E6%B8%B8%E6%8C%87%E5%8D%97%E3%80%82%E6%88%91%E4%BC%9A%E6%8A%8A%E6%88%91%E7%9A%84%E4%BD%8D%E7%BD%AE%E5%E3%80%82%E2%80%9D%0A&format=json
    +------------------------------------

```
