### ISSUE TITLE
 Error refreshing session ID, retrying in 1 minute... 错误

### ISSUE THREAD

**Issue by gdmec07150752** [nashsu/FreeAskInternet#42]
把最新的版本部署到了vps上，是美国ip，可输入后，迟迟没有返回答案。
看了日志，提示 Error refreshing session ID, retrying in 1 minute...。
请问是什么原因，如何解决
![image](https://github.com/nashsu/FreeAskInternet/assets/21993149/95107366-8d11-499a-ac06-f49e979503a4)

**Comment by nashsu** [comment]
VPS大部分都会被禁，家庭正常IP才有可能正常使用，可以更新最新版尝试更多模型

**Comment by gdmec07150752** [comment]
> VPS大部分都会被禁，家庭正常IP才有可能正常使用，可以更新最新版尝试更多模型

 2024-04-10 13:32:23,041 ERROR:searx.engines.wikidata: Fail to initialize
freeaskinternet-searxng-1             | Traceback (most recent call last):
freeaskinternet-searxng-1             |   File "/usr/local/searxng/searx/network/__init__.py", line 95, in request
freeaskinternet-searxng-1             |     return future.result(timeout)
freeaskinternet-searxng-1             |            ^^^^^^^^^^^^^^^^^^^^^^

**Comment by wensley** [comment]
刚更新镜像 重新部署了，用的甲骨文美区，
`{
  "error": true,
  "message": "Error in input stream"
}
`
`{
  "error": true,
  "message": "empty response"
}
`
```
 +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "/usr/local/lib/python3.9/site-packages/sse_starlette/sse.py", line 270, in wrap
    |     await func()
    |   File "/usr/local/lib/python3.9/site-packages/sse_starlette/sse.py", line 251, in stream_response
    |     async for data in self.body_iterator:
    |   File "/usr/local/lib/python3.9/site-packages/starlette/concurrency.py", line 65, in iterate_in_threadpool
    |     yield await anyio.to_thread.run_sync(_next, as_iterator)
    |   File "/usr/local/lib/python3.9/site-packages/anyio/to_thread.py", line 56, in run_sync
    |     return await get_async_backend().run_sync_in_worker_thread(
    |   File "/usr/local/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 2144, in run_sync_in_worker_thread
    |     return await future
    |   File "/usr/local/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 851, in run
    |     result = context.run(func, *args)
    |   File "/usr/local/lib/python3.9/site-packages/starlette/concurrency.py", line 54, in _next
    |     return next(iterator)
    |   File "/app/server.py", line 152, in predict
    |     for token in free_ask_internet.ask_internet(query=query):
    |   File "/app/free_ask_internet.py", line 219, in ask_internet
    |     content_list = search_web_ref(query,debug=debug)
    |   File "/app/free_ask_internet.py", line 99, in search_web_ref
    |     raise ex
    |   File "/app/free_ask_internet.py", line 39, in search_web_ref
    |     response.raise_for_status()
    |   File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    |     raise HTTPError(http_error_msg, response=self)
    | requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http://searxng:8080/?q=%3Aall+%21general+%E6%88%91%E6%83%B3%E8%AE%A9%E4%BD%A0%E5%81%9A%E4%B8%80%E4%B8%AA%E6%97%85%E6%B8%B8%E6%8C%87%E5%8D%97%E3%80%82%E6%88%91%E4%BC%9A%E6%8A%8A%E6%88%91%E7%9A%84%E4%BD%8D%E7%BD%AE%E5%E3%80%82%E2%80%9D%0A&format=json
    +------------------------------------

```
