### ISSUE TITLE
searxng启动的时候， 总是报告 httpx.TimeoutException: Timeout错误

### ISSUE THREAD

**Issue by junmingzha** [nashsu/FreeAskInternet#56]
searxng-1             | Traceback (most recent call last):
searxng-1             |   File "/usr/local/searxng/searx/search/processors/abstract.py", line 73, in initialize
searxng-1             |     self.engine.init(get_engine_from_settings(self.engine_name))
searxng-1             |   File "/usr/local/searxng/searx/engines/wikidata.py", line 774, in init
searxng-1             |     jsonresponse = send_wikidata_query(query)
searxng-1             |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
searxng-1             |   File "/usr/local/searxng/searx/engines/wikidata.py", line 161, in send_wikidata_query
searxng-1             |     http_response = get(SPARQL_ENDPOINT_URL + '?' + urlencode({'query': query}), headers=get_headers())
searxng-1             |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
searxng-1             |   File "/usr/local/searxng/searx/network/__init__.py", line 164, in get
searxng-1             |     return request('get', url, **kwargs)
searxng-1             |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
searxng-1             |   File "/usr/local/searxng/searx/network/__init__.py", line 97, in request
searxng-1             |     raise httpx.TimeoutException('Timeout', request=None) from e
searxng-1             | httpx.TimeoutException: Timeout

**Comment by wolfg1969** [comment]
应该是你的网络环境无法访问 Wikidata 网站。

**Comment by junmingzha** [comment]
我加了https_proxy和http_proxy, 在env里，但也不行，到docker 里，是可以访问wiki的。这里的httpx timeout，代理如何设置？

**Comment by whcjimmy** [comment]
把 searxng/settings.yml 當中 outgoing 的 request_timeout 設定成 5.0 可以避開這個問題

參考：
https://github.com/searxng/searxng/issues/334#issuecomment-922730089

**Comment by Kay100** [comment]
> 我加了https_proxy和http_proxy, 在env里，但也不行，到docker 里，是可以访问wiki的。这里的httpx timeout，代理如何设置？

大哥，我也是这个问题哈，一样，你后来结局了吗，我按照下面的提示去修改了超时，也还是不行的。应该不是超时的不行，我也怀疑还是代理配置方法的问题。

**Comment by wuyunzzz** [comment]
我也有这个问题

**Comment by wuyunzzz** [comment]
> > 我加了https_proxy和http_proxy, 在env里，但也不行，到docker 里，是可以访问wiki的。这里的httpx timeout，代理如何设置？
> 
> 大哥，我也是这个问题哈，一样，你后来结局了吗，我按照下面的提示去修改了超时，也还是不行的。应该不是超时的不行，我也怀疑还是代理配置方法的问题。

大哥，你解决了这个问题吗
